# Header Menu
menu:
  Home: /
  Sobre: /about

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: ramon-santos
google_analytics: AA-12345678-0
swiftype_install_key:

# Social
social:
  github: https://github.com/ramonsantos
  twitter: https://twitter.com/ramonsantos_x
  facebook: https://www.facebook.com/ramonsantos.dev
  rss: atom.xml
  linkedin: https://br.linkedin.com/in/Ramon-Santos
  stackoverflow: http://pt.stackoverflow.com/users/38532/ramonsantos

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "123456789012345678" # as a string, from https://twitter.com/settings/widgets
twitter_username: ramonsantos_x # twitter username without the @
default_author: Ramon Santos

about:
phone:
email: ramonsantos.pe@gmail.com
address_1:
address_2:
address_3:
skype:
lat:
long:

language: pt
